websocket/main.go
Should be `SendString()` in version 2
=> fix: wrong method name

cloud-run/cloudbuild.yaml
Found out one missing config, that will cause command `glcoud build submit` not work
=> add missing config on cloudbuild.yaml

graceful-shutdown/main.go
When deployed in a container (and e.g. in a K8s cluster), the signal for a shutdown usually is SIGTERM. I would add this to the recipe because I think this is a very common use case. Btw I absolutely love fiber! Keep up the good work :)
=> Add termination signal for graceful shutdown

k8s/Dockerfile
The copy origin in line 13 should be either `0` or stage 0 should be annotated with `AS builder`, otherwise this build leads to an error.
=> Fix missing stage name

k8s/Dockerfile
The ca-certificates are necessary to establish TLS encrypted connections with the HTTP client or other TCP connection e.g. to a database. Although they are not required in this particular example, I believe that many will still run into this problem. The Docker best practices documentation about [multi-stage builds](https://docs.docker.com/develop/develop-images/multistage-build/#use-multi-stage-builds) also adds the certificates.
=> Install ca-certificates to be able to use TLS

websocket-chat/main.go
removing duplicate colon to address.
Following error while running the application : 
_listen tcp4: address ::8080: too many colons in address_
=> Removing duplicate colon in address in main.go under websocket-chat

graceful-shutdown/main.go
If we use keep-alive clients like a Postman or other clients with keep-alive headers, the Fiber server will be never shutdown.
I suggest adding the IdleTimeout because by default this value is infinity.
Also, I add 
```
fmt.Println("Fiber was successful shutdown.")
```
=> Add timeout for handling keep-alive clients

websocket-chat/main.go
Now in the websocket-chat recipe, `unregister = make(chan *websocket.Conn)`, so it's a blocked channel.
In the broadcast case, if we fail to send message to a client, we can't unregister the client by `unregister <- connection`, which will cause deadlock.
```go
case message := <-broadcast:
log.Println("message received:", message)
// Send the message to all clients
for connection := range clients {
if err := connection.WriteMessage(websocket.TextMessage, []byte(message)); err != nil {
log.Println("write error:", err)
unregister <- connection
connection.WriteMessage(websocket.CloseMessage, []byte{})
connection.Close()
}
}
case connection := <-unregister:
// Remove the client from the hub
delete(clients, connection)
log.Println("connection unregistered")
}
```
Instead, we need to delete it …
=> 👷 Fix deadlock in websocket-chat recipe

unit-test/main_test.go
The body is a combination of HTTP method + path now.
https://github.com/gofiber/fiber/blob/9b3662eae0e348892e28780b001ec146bc33be36/router.go#L133
=> Fix broken `unit-test` example

clean-architecture/api/app.go, clean-architecture/api/routes/book.go
Hi!
Thanks for your excellent work. I'm new to both Go and Go Fiber and when I was trying to run the "clean-architecture" recipe, I found these problems:
1. The server did not start and the app just exited without any error. It turned out that the port "8080" was already in use.
2. I made a request to the `GET /api/books` endpoint and the server took roughly about 20 seconds to respond because the Mongo client could not connect to the database server and there's no error about it neither in the response payload nor the stderr.
For problem 1., I fix it by wrapping the `app.Listen()` with the `log.Fatal()` in [
a2deee6](https://github.com/gofiber/recipes/commit/a2deee6904c6cef7bee9cb2ef452503b6cac834b).
And for problem 2., I make it to respond with the error message in the response payload …
=> Fix confusing behaviors for newbie in the clean-architecture recipe

auth-jwt/README.md
Fixed a small Markdown syntax error regarding the Link in the auth-jqt/README.md file
=> Fix Markdown Link

graphql/graph/generated/generated.go, graphql/server.go
These changes allow this example to work with the [https://github.com/99designs/gqlgen](https://github.com/99designs/gqlgen) package
=> Update graphql example for compatibility with 99designs/gqlgen package

sse/main.go
Fix sse recipe: Refreshing page in web browser will establish a new SSE connection, but only (the last) one is alive, so dead connections must be closed.
=> Fix sse recipe: close dead connection

.github/dependabot.yml
Currently dependabot can't update dependencies recursively as stated here: https://github.com/dependabot/dependabot-core/issues/2178 https://github.com/dependabot/dependabot-core/issues/2824
This PR adds each directory to dependabot.yml so the go dependencies get updated. 
Fixes #171 
* Git clone this repo: `git clone git@github.com:gofiber/recipes.git`
* Run the following script `python3 create_dependabot.py`
```python3
import os
pwd = os.getcwd()
print(f"Current working directory: {pwd}")
dirs = [entry.name for entry in os.scandir(os.path.join(pwd, "recipes")) if entry.is_dir()]
for entry in dirs:
print('  - package-ecosystem: "gomod"')
print(f'    directory: "/{entry}"')
print('    schedule:')
print('      interval: "daily"')
```
=> Add dependabot support to each recipe

gorm-postgres/database/database.go
on this error handling, there's no need to use os.Exit() function; because log.Fatal() already use os.Exit()
This os.Exit() is unreachable.
=> fix: remove unreachable os.Exit function

auth-jwt/handler/auth.go
`auth-jwt/handler/auth.go`
Should omit comparison to bool constant, can be simplified to valid(identity) as it is returning **bool**
```go
// From
if valid(identity) == true {
}
// To
if valid(identity) {
}
```
=> Should omit comparison to bool constant in auth-jwt/handler/auth.go

air/.air.linux.conf
Little fix to avoid this error:
=> fixing `/bin/sh: application not found`

swagger/routes/routes.go
While working on the project, I discovered an issue in the 'routes.go' file in the swagger example where the Swagger Handler method was not correctly referenced.
Changes
There is a change on line 20 of the 'routes.go' file. The incorrect usage of 'Handler' was replaced with 'HandlerDefault', as documented in the official [Fiber Swagger package](https://pkg.go.dev/github.com/arsmn/fiber-swagger/v2#section-readme).
- app.Get ("/docs/*", swagger. Handler)
+ app.Get ("/docs/*", swagger. HandlerDefault)
=> FIX: swagger initialization in swagger Example

docker-mariadb-clean-arch/go.mod, docker-mariadb-clean-arch/go.sum, docker-mariadb-clean-arch/internal/auth/handler.go
Updated the `golang-jwt/jwt` to v5 to fix the following error in the endpoint `/api/v1/auth/private`
```
endpoint: `/api/v1/auth/private`
interface conversion: interface {} is *jwt.Token, not *jwt.Token (types from different packages)
```
=> docker-mariadb-clean-arch: fix broken endpoint `/api/v1/auth/private`

aws-sam-container/README.md, aws-sam-container/samconfig.toml, aws-sam/README.md, aws-sam/app/go.mod, aws-sam/samconfig.toml, aws-sam/template.yaml
- Runtime Update: Switched Lambda function runtime from go1.x to provided.al2023, aligning with AWS's latest support and performance enhancements.
- README Update: Added instructions for setting up public access permissions on Lambda function URLs using aws lambda add-permission.
These updates respond to the AWS deprecation of the Go 1.x runtime, ensuring our Lambda functions remain supported and secure. The README enhancement clarifies how to manage access permissions for function URLs, improving usability and deployment workflows.
Ref: [Migrating AWS Lambda functions from the Go1.x runtime to the custom runtime on Amazon Linux 2](https://aws.amazon.com/cn/blogs/compute/migrating-aws-lambda-functions-from-the-go1-x-runtime-to-the-custom-runtime-on-amazon-linux-2/)
Testing
Confirmed the …
=> chore(Recipes): Update AWS Lambda Go Runtime to Amazon Linux 2023 and Revise README for URL Permissions

geoip/handlers/geo.go, geoip/main.go
Why? 
geoip example ,the route in the page request does not match the route in the code
What? 
- replaced route to handle route `/geo` instead of `/geo/:ip?`
- replaced Params with [Query](https://docs.gofiber.io/api/ctx#query) to retrieve the ip
Fixes #2222
=> fix: route mismatch in GeoIP example due to incorrect path and query
