- README.md
- go.mod
- unit-test/main.go
- unit-test/main_test.go
A new recipe how to unit test routes with fiber.
> Add example for unit testing with fiber

- README.md
- air/.air.linux.conf
- air/.air.windows.conf
- air/main.go
Add Live Reloading example using [Air](https://github.com/cosmtrek/air)
> Add Live Reloading (Air) example

- postgresql/main.go
Fix query typo for insert process in pg example in recipes
> Fix query typo in line 101 from salry to salary

- jwt/database/database.go
Adding the docker-nginx-loadbalancer recipe to the content table.
> Update Content Table

- README.md
- websocket-chat/README.md
- websocket-chat/home.html
- websocket-chat/main.go
> Added WebSocket Chat Example

- upload-file/single_relative_path/main.go
- upload-file/single_relative_path/uploads/sample.txt
This fixes #47 
_Adds a sample example to show how one can specify a relative path to store file uploads_
> Adds example for relative path file uploads (#47)

- auth-jwt/go.mod
- auth-jwt/go.sum
- auth-jwt/middleware/auth.go
Fixed some type errors, which was introduced while migrating recipes to v2
> auth-jwt: fixed type errors

- clean-architecture/.gitignore
- clean-architecture/api/app.go
- clean-architecture/api/routes/book.go
- clean-architecture/go.mod
- clean-architecture/pkg/book/repository.go
- clean-architecture/pkg/book/service.go
- clean-architecture/pkg/entities/book.go
- add clean-architecture example
- uses fiber v2.0 
- uses mongodb for example
> add: clean-architecture

- optional-parameter/main.go
Hello, I made a simple recipe for optional parameters that receives an id and returns a customized string for the user with that id :)
That can be the base for more complex REST applications
> Add optional parameter recipe

- k8s/Dockerfile
forget to add `Dockerfile` on https://github.com/gofiber/recipes/pull/62
> add dockerfile

- mongodb/main.go
Had fixed this whilst I playing around with the MongoDB driver. Thought I may as well PR it!
> recipes/mongodb :alien: fiber 2.0 fixes

- graceful-shutdown/README.md
- graceful-shutdown/main.go
previous one, i tested gracefully shutdown and i found it is not work. so i fix some code and it is ok.
app.listen should be running in goroutine. channel waiting for interrupt signal to gracefully shutdown
> fix interrupt signal to gracefully shutdown

- graceful-shutdown/go.sum
- graceful-shutdown/main.go
> Fix missing syscall in import

- prefork/main.go
when i start read some recipes and try it out, i figured out that the console not easy to read, than i add backslash in the end of fmt.Printf
Thank you
> Add enter for easy reading

- mysql/main.go
Update comments around MySQL queries as they were all the same "Insert Employee into database" even when getting from the database or deleting from it. This might be confusing to people quickly skimming the recipe
> Update comments around MySQL queries

- README.md
- csrf/.gitignore
- csrf/README.md
- csrf/go.mod
- csrf/main.go
- csrf/routes/evilServer.go
- csrf/routes/mainServer.go
- csrf/views/evil-examples.html
- csrf/views/home.html
- csrf/views/layouts/main.html
- csrf/views/login.html
- csrf/views/malicious-form.html
add a csrf example according to the example of https://github.com/Learn-by-doing/csrf-examples
> add a csrf example

- mongodb/main.go
Hello, I was using a prescription and I noticed there was no retrieval of a document in the private collection from the database. and i did.
> Get once Quote

- README.md
- clean-architecture/README.md
- clean-architecture/api/app.go
- clean-architecture/api/handlers/book_handler.go
- clean-architecture/api/presenter/book.go
- clean-architecture/api/routes/book.go
- clean-architecture/go.mod
- clean-architecture/pkg/book/repository.go
- clean-architecture/pkg/book/service.go
- clean-architecture/pkg/entities/book.go
- Closes #141 
- Remove bindings from example
- Add Handlers and Presenters to Clean Architecture Example
- Add documentation for Clean Architecture Example
> recipe(clean-architecture): fix bindings and add docs

- mongodb/main.go
> wrong operator (for mongodb)

- geoip/handlers/geo.go
- geoip/main.go
to allow the app to be directly deployed to Heroku-like PaaS
> Fix geoip missing import and configure port with env variable

- auth-jwt/handler/auth.go
I tried the recipe with my project, unfortunately, it doesn't work as expected, hence, I push a fix for it.
my ref project: https://github.com/PeterNgTr/go-fiber-fun/blob/main/middleware/auth.go
> improve login func

- fiber-bootstrap/README.md
https://github.com/gofiber/recipes/issues/776
> add Fiber bootstrap setup instructions

- oauth2-google/auth/auth.go
> fix: some predefined functions

- graphql/main.go
Graphql example was not working since it was accepting directly query in the body, but it's crafted into a JSON object on the `query` key.
I also implemented the `GET` style endpoint.
> fix(graphql): Fix input format

- mongodb/main.go
Hello.
While testing mongodb while referring to the code, I see a deprecated function and update it.
Change Quick Start link
Remove deprecated function
> 👽️ Update mongodb recipe

- auth-docker-postgres-jwt/handler/api.go
- auth-jwt/handler/api.go
Just a simple typo fix. I'm not sure if there are specific contributing guidelines I should follow, feel free to link them if there's something wrong with my commit/PR.
> fix typo hanlde->handle in jwt recipe
